@SoftwareCenter.Api_HostAddress = http://localhost:1337

POST {{SoftwareCenter.Api_HostAddress}}/vendors
Accept: application/json
Content-type: application/json

{
    "name": "Microsoft",
    "url": "https://www.microsoft.com",
    "pointOfContact": 
    {
        "name": "Satya",
        "phone": "800 small-boss",
        "email": "satya@microsoft.com"
    }
}


###
GET {{SoftwareCenter.Api_HostAddress}}/vendors/a0ab084e-d6e3-4e5a-97fe-aaf0933491da

###
GET {{SoftwareCenter.Api_HostAddress}}/vendors/